import React, { useEffect, useState } from "react";
import * as axios from "axios";
import { useRouter } from 'next/router';
import { useSelector } from "react-redux";
import Header from '../components/Header';
import Footer from "../components/Footer";
import Head from 'next/head';
import styles from "../../styles/Users.module.css";

/* =========================================================================== */
const UserDetails = ({ user }) => {
  const router = useRouter();
  const { id } = router.query;
  const [user] = useSelector((state) => state.users.filter((item) => item.id === parseInt(id)));

  return (
    <div className={styles.App}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.user__main}>
        <h2 className={styles.user__fullname}>{ user.first_name } { user.last_name }</h2>
        <div>
          <img className={styles.avatar} src={user.avatar} alt=""/>
        </div>
        <div className={styles.user__email}>{user.email}</div>
      </main>
      <Footer />
    </div>
  )
}

/*
export async function getStaticPaths() {
  const res = await axios.get("https://reqres.in/api/users/");
  const users = await res.data.data;

  const paths = users.map((user) => ({
    params: { id: user.id.toString() }
  }))

  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps({ params }) {

  const res = await axios.get(`https://reqres.in/api/users/${params.id}`);
  const user = res.data.data;

  return {
    props: {
      user
    }
  }
}
*/


export default UserDetails;
