import React from "react";
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { useRouter } from "next/router";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { useSelector } from "react-redux";
import styles from "../styles/Profile.module.css";


export default function Profile() {
  const router = useRouter();
  const token = useSelector((state) => state.login.credentials.token);

  if (!token) {
    router.push("/login");
  }

  return (
    <div className={styles.App}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        Private Info from User profile
      </main>
      <Footer />
      </div>
  )
}
